versions = [
    "latest-nightly",
]

configurations = [
    "default.toml",
]

[specs]
fixtures = [
    "../specs/group_by.toml"
]
queries = [
    "../specs/group_by.toml",
    "../specs/aggregate.toml",
    "../specs/window_functions.toml",
    "../specs/like.toml",
    "../specs/regex.toml",
    "../specs/queries.toml",
    "../specs/select.toml",
    "../specs/in_string.toml",
    "../specs/in_numeric.toml",
    "../specs/order_by_no_limit.toml",
    "../specs/select/simple_subquery.toml",
    "../specs/select/correlated_subqueries.toml",
]
full = [
    "../specs/insert_single.py",
    "../specs/insert_unnest.py",
    "../specs/insert_bulk.toml",
    "../specs/delete_single.py",
    "../specs/delete_bulk.py",
    "../specs/any.py",
    "../specs/generated_columns.toml",
    "../specs/create_partitions.py",
    "../specs/information_schema.py",
    "../specs/update_single.py",
    "../specs/update_bulk.py",
    "../specs/partitioned_bulk_insert.py",
    "../specs/upsert_single.py",
    "../specs/upsert_bulk.py",
    "../specs/joins.toml",
    "../specs/joins-many_tables.toml",
    "../specs/select/joins_aggregations.toml",
    "../specs/outer-joins.toml",
    "../specs/delete/*.py",
    "../specs/delete/*.toml",
    "../specs/select/*.py",
    "../specs/select/sys_select.toml",
    "../specs/select/array_access.toml",
    "../specs/select/count.toml",
    "../specs/select/disabled_doc_values.toml",
    "../specs/select/hash_joins.toml",
    "../specs/select/hyperloglog.toml",
    "../specs/select/joins_aggregations.toml",
    "../specs/select/sys_allocations.toml",
    "../specs/select/sys_health.toml",
    "../specs/select/sys_select.toml",
    "../specs/select/sys_shards.toml",
    "../specs/in_subquery.toml",
    "../specs/union.toml",
    "../specs/ignore3vl.toml",
    "../specs/lookup_join.toml",
]
