[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-0000*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = "select count(*) from uservisits"
iterations = 200

[[queries]]
statement = '''select count("cCode") from uservisits'''
iterations = 50

[teardown]
statements = ["drop table uservisits"]
