[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-0000*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = '''select "cCode", count(*) from uservisits group by "cCode"'''
iterations = 100

[[queries]]
statement = '''select min("adRevenue") from uservisits group by "cCode"'''
iterations = 100

[[queries]]
statement = '''select max("adRevenue") from uservisits group by "cCode"'''
iterations = 100

[[queries]]
statement = '''select avg("adRevenue") from uservisits group by "cCode"'''
iterations = 100

[[queries]]
statement = '''select count(distinct "searchWord") from uservisits group by "cCode"'''
iterations = 100

[[queries]]
statement = '''select arbitrary("searchWord") from uservisits group by "cCode"'''
iterations = 100

[teardown]
statements = ["drop table uservisits"]
