[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00001*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00002*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00003*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00004*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00005*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = "select * from uservisits limit 10"
iterations = 1000

[[queries]]
statement = "select * from uservisits limit 100"
iterations = 1000

[[queries]]
statement = "select * from uservisits limit 100"
concurrency = 20
iterations = 1000

[[queries]]
statement = "select * from uservisits limit 1000"
iterations = 1000

[[queries]]
statement = "select * from uservisits limit 10000"
iterations = 500

[[queries]]
statement = "select * from uservisits limit 100000"
iterations = 250

[[queries]]
statement = '''select * from uservisits order by "adRevenue" limit 10'''
iterations = 1000

[[queries]]
statement = '''select * from uservisits order by "adRevenue" limit 10'''
iterations = 1000
concurrency = 20

[[queries]]
statement = "select count(*) from uservisits"
iterations = 1000

[[queries]]
statement = '''select count("cCode") from uservisits'''
iterations = 1000

[[queries]]
statement = '''select count("sourceIP") from uservisits'''
iterations = 1000

[[queries]]
statement = '''select "cCode", count(*) from uservisits group by 1 order by 2 desc limit 20'''
iterations = 500

[[queries]]
statement = '''select extract(day from "visitDate"), count(*) from uservisits group by 1 order by 2 desc limit 20'''
iterations = 500


[teardown]
statements = ["drop table uservisits"]
