[setup]
statements = [
   '''create table tbl (dummy_col_for_gen_ser_insert int, obj OBJECT(STRICT) AS ("prop" TEXT))''',
   '''insert into tbl(dummy_col_for_gen_ser_insert) (select * from generate_series(1,100000))''',
   '''update tbl set obj['prop']=dummy_col_for_gen_ser_insert%1000::text'''
]

[[queries]]
statement = "select count(*) from (select obj['prop'] as prop from tbl) t where prop = '500' limit 100"
iterations = 1000
concurrency = 15

[[queries]]
statement = "select count(*) from (select obj['prop'] from tbl) t where obj['prop']='500' limit 100"
iterations = 1000
concurrency = 15


[teardown]
statements = [
  "drop table tbl"
]