# Requires the "uservisits" table. Load it once with:
#   venv/bin/cr8 run-spec specs/select/_load_uservisits.toml localhost:4200

[[queries]]
name = "count-two-distinct-original"
statement = '''
    SELECT COUNT(DISTINCT "sourceIP"), COUNT(DISTINCT "destinationURL")
    FROM uservisits;
'''
iterations = 5


[[queries]]
name = "count-two-distinct-replaced"
statement = '''
  SELECT a.agg1, b.agg2
  FROM (
      SELECT COUNT("sourceIP") AS agg1
      FROM (SELECT "sourceIP" FROM uservisits GROUP BY "sourceIP") t1
  ) a
  CROSS JOIN (
      SELECT COUNT("destinationURL") AS agg2
      FROM (SELECT "destinationURL" FROM uservisits GROUP BY "destinationURL") t2
  ) b;
'''
iterations = 5
