[setup]
statement_files = ["../sql/uservisits.sql"]
statements = [
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00000.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00005.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00006.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00007.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00008.gz' with (compression = 'gzip')",
    "copy uservisits from 'file:///home/haris/projects/crate/test-data/uservisits/part-00009.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]

# [[queries]]
# name = "count-distinct-cCode-original"
# statement = '''
#     select count(distinct "cCode") from uservisits
# '''
# concurrency = 15
# iterations = 300

[[queries]]
name = "count-distinct-duration-replaced"
statement = '''
    select count("duration") 
    from (select "duration" from uservisits group by "duration") temp
'''
concurrency = 15
iterations = 300

# [[queries]]
# name = "count-distinct-cCode-hacky"
# statement = '''
#     select count(c) 
#     from (select "cCode", count(*) as c from uservisits group by "cCode") temp
# '''
# concurrency = 15
# iterations = 300

# [[queries]]
# name = "count-distinct-cCode-count-ones"
# statement = '''
#     select count(*) 
#     from (select 1 from uservisits group by "cCode") temp
# '''
# concurrency = 15
# iterations = 300

# [teardown]
# statements = ["drop table if exists uservisits"]
