[setup]
statement_files = ["../sql/uservisits_1_shard.sql"]
statements = [
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00000.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00005.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00006.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00007.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00008.gz' with (compression = 'gzip')",
    "copy uservisits_1_shard from 'file:///home/haris/projects/crate/test-data/uservisits/part-00009.gz' with (compression = 'gzip')",
    "refresh table uservisits_1_shard"
]

[[queries]]
name = "count-distinct-cCode"
statement = '''
    select count(distinct "cCode") from uservisits_1_shard
'''
concurrency = 5
iterations = 150

[[queries]]
name = "count-distinct-destinationURL"
statement = '''
    select count(distinct "destinationURL") from uservisits_1_shard
'''
concurrency = 5
iterations = 150

[[queries]]
name = "count-distinct-sourceIP"
statement = '''
    select count(distinct "sourceIP") from uservisits_1_shard
'''
concurrency = 5
iterations = 150

# [teardown]
# statements = ["drop table if exists uservisits_1_shard"]
