# Requires the "uservisits" table. Load it once with:
#   venv/bin/cr8 run-spec specs/select/_load_uservisits.toml localhost:4200

# [[queries]]
# name = "count-distinct-cCode-original"
# statement = '''
#     select count(distinct "cCode") from uservisits
# '''
# concurrency = 15
# iterations = 300

[[queries]]
name = "count-distinct-duration-replaced"
statement = '''
    select count("duration") 
    from (select "duration" from uservisits group by "duration") temp
'''
concurrency = 15
iterations = 300

# [[queries]]
# name = "count-distinct-cCode-hacky"
# statement = '''
#     select count(c) 
#     from (select "cCode", count(*) as c from uservisits group by "cCode") temp
# '''
# concurrency = 15
# iterations = 300

# [[queries]]
# name = "count-distinct-cCode-count-ones"
# statement = '''
#     select count(*) 
#     from (select 1 from uservisits group by "cCode") temp
# '''
# concurrency = 15
# iterations = 300
