[setup]
statement_files = ["../sql/huge_arrays.sql"]

    [[setup.data_cmds]]
    target = "huge_arrays"
    cmd = ['generators/huge_arrays.sh']
    bulk_size = 500

[[queries]]
statement = "select xs from huge_arrays"
iterations = 500


[teardown]
statements = ["drop table if exists huge_arrays"]
