# Gives a good indication of our parser/analyzer/planner/execution-setup-overhead/collect-expressions
[setup]
statements = [
    # create some shards so sys.allocations will contain some rows
    "create table t_shards (id int, name string, value float) clustered into 100 shards with (number_of_replicas=0)",
]

[[queries]]
statement = "select name from sys.cluster"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select name from sys.cluster"
iterations = 15000
concurrency = 15

[[queries]]
statement = "select * from sys.nodes"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.nodes"
iterations = 15000
concurrency = 15

[[queries]]
statement = "select * from sys.allocations"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.jobs"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.operations"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.jobs_metrics"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.checks"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.node_checks"
iterations = 5000
concurrency = 1

[[queries]]
statement = "select * from sys.summits"
iterations = 2000
concurrency = 1


[teardown]
statements = ["drop table if exists t_shards"]
