[setup]
statement_files = ["../sql/wide.sql"]

    [[setup.data_cmds]]
    target = "wide"
    cmd = ['generators/wide.sh']
    bulk_size = 500


[[queries]]
statement = "select x1788, x1200 from wide limit 100"
iterations = 800
concurrency = 10

[[queries]]
statement = "select x1788, x1200 from wide limit 1500"
iterations = 800
concurrency = 10


[teardown]
statements = ["drop table if exists wide"]
