[setup]
statement_files = ["hll.sql"]

    [[setup.data_cmds]]
    target = "hll"
    cmd = ['specs/memory_pressure/gen_data.sh']
    bulk_size = 1000
    concurrency = 25


[[queries]]
statement = """
SELECT
    custom_user_id,
    hyperloglog_distinct(id, 8)
FROM
    hll
WHERE
    _docid % 10 = 0
GROUP BY
    1
ORDER BY
    2 DESC
LIMIT 20
"""
concurrency = 2
iterations = 500


[[queries]]
statement = """
SELECT
    custom_user_id,
    hyperloglog_distinct(id, 8)
FROM
    hll
WHERE
    _docid % 10 = 0
GROUP BY
    1
ORDER BY
    2 DESC
LIMIT 20
"""
concurrency = 10
iterations = 500


[teardown]
statements = ["drop table if exists hll"]
