[setup]
statements = ["create table t (id int, value string)"]

    [[setup.data_files]]
    target = "t"
    source = "../data/id_int_value_str.json"
    bulk_size = 10000


[[queries]]
statement = "delete from t where id < 300"
iterations = 1
concurrency = 1


[teardown]
statements = ["drop table t"]
