[setup]
statement_files = ["../sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00001*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00002*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00003*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00004*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00005*' with (compression = 'gzip')",
    "refresh table uservisits"
]


[[queries]]
statement = '''select * from (select * from uservisits order by "adRevenue" asc limit 500) t order by "adRevenue" desc limit 100
'''
iterations = 2000


[[queries]]
statement = '''select * from (select * from uservisits order by "adRevenue" asc limit 200000) t order by "adRevenue" desc limit 100
'''
iterations = 50


[teardown]
statements = ["drop table uservisits"]
