[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00005.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]


[[queries]]
name = "is-distinct-from"
statement = '''select count(*) from uservisits where "sourceIP" is distinct from '74.160.74.213' '''
concurrency = 10
iterations = 100

[[queries]]
name = "neq"
statement = '''select count(*) from uservisits where "sourceIP" != '74.160.74.213' '''
concurrency = 10
iterations = 100

[[queries]]
name = "is-not-distinct-from"
statement = '''select count(*) from uservisits where "sourceIP" is not distinct from '74.160.74.213' '''
concurrency = 10
iterations = 100

[[queries]]
name = "eq"
statement = '''select count(*) from uservisits where "sourceIP" = '74.160.74.213' '''
concurrency = 10
iterations = 100

[teardown]
statements = ["drop table if exists uservisits"]
