[setup]
statements = [
  "create table t090 (x long) clustered into 5 shards",
  "create table t075 (x long) clustered into 5 shards",
  "create table t050 (x long) clustered into 5 shards",
  "create table t025 (x long) clustered into 5 shards"
]

  [[setup.data_files]]
  target = "t090"
  source = "data/t_090.json.gz"

  [[setup.data_files]]
  target = "t075"
  source = "data/t_075.json.gz"

  [[setup.data_files]]
  target = "t050"
  source = "data/t_050.json.gz"

  [[setup.data_files]]
  target = "t025"
  source = "data/t_025.json.gz"


[[queries]]
statement = "select count(*) from (select distinct x from t090) t"
concurrency = 10
iterations = 200

[[queries]]
statement = "select count(*) from (select distinct x from t075) t"
concurrency = 10
iterations = 200

[[queries]]
statement = "select count(*) from (select distinct x from t050) t"
concurrency = 10
iterations = 200

[[queries]]
statement = "select count(*) from (select distinct x from t025) t"
concurrency = 10
iterations = 200

[teardown]
statements = [
  "drop table t090",
  "drop table t075",
  "drop table t050",
  "drop table t025"
]
