[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00005.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
name = "avg, sum, min and group by a single numeric key"
statement = '''select avg("adRevenue"), sum("adRevenue"), min("adRevenue") from uservisits group by "duration"'''
concurrency = 10
iterations = 1000

[[queries]]
name = "avg and group by a single numeric key"
statement = '''select avg("adRevenue") from uservisits group by "duration"'''
concurrency = 10
iterations = 1000

[[queries]]
name = "avg and group by string and numeric keys"
statement = '''select avg("adRevenue") from uservisits group by "cCode", "duration"'''
concurrency = 10
iterations = 1000

[[queries]]
name = "count star and group by a single string key"
statement = '''select "cCode", count(*) from uservisits group by "cCode"'''
concurrency = 15
iterations = 100

[[queries]]
statement = '''select min("adRevenue") from uservisits group by "cCode"'''
concurrency = 15
iterations = 100

[[queries]]
statement = '''select avg("adRevenue") from uservisits group by "cCode", "lCode"'''
concurrency = 15
iterations = 100

[[queries]]
statement = '''select count(distinct "searchWord") from uservisits group by "cCode"'''
concurrency = 5
iterations = 100

[teardown]
statements = ["drop table uservisits"]
