[setup]
statements = [
  "create table t090 (x long) clustered into 5 shards",
  "insert into t090 (x) (select x % 9000000 from generate_series(0, 9999999) as t (x))",
  "refresh table t090",
  "OPTIMIZE TABLE t090 WITH (max_num_segments = 1)"
]


[[queries]]
name = "count_distinct_t090"
statement = "select count(distinct x) from t090"
concurrency = 1
iterations = 50

[teardown]
statements = [
  "drop table if exists t090"
]
