[setup]
statement_files = ["sql/articles.sql", "sql/colors.sql"]
statements = [
    "copy articles from 'https://cdn.crate.io/downloads/datasets/benchmarks/articles_0.json.gz' with (compression = 'gzip')",
    "copy colors from 'https://cdn.crate.io/downloads/datasets/benchmarks/colors_0.json.gz' with (compression = 'gzip')",
    "refresh table articles, colors"
]

[[queries]]
statement = "select * from articles where id in (select id from colors where coolness > 0) limit 10000"
iterations = 200

[[queries]]
statement = "select * from articles where id not in (select id from colors where coolness > 0) limit 10000"
iterations = 200

[teardown]
statements = ["drop table articles", "drop table colors"]
