[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00005.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = "select * from uservisits where \"sourceIP\" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
args = [
    '1.45.41.3',
    '53.187.68.171',
    '187.251.83.215',
    '131.49.205.110',
    '225.119.100.49',
    '64.186.49.18',
    '225.217.19.167',
    '206.195.34.147',
    '29.152.132.228',
    '199.109.201.168',
]
iterations = 1000

[teardown]
statements = ["drop table uservisits"]
