[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/1node/uservisits/part-00001.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]


[[queries]]
statement = """select * from uservisits
where
    \"cCode\" = (select \"cCode\" from uservisits where \"sourceIP\" = '162.122.2.17')
limit 100
"""
iterations = 10000

[teardown]
statements = ["drop table uservisits"]
