[setup]
statement_files = ["sql/articles.sql", "sql/colors.sql"]
statements = [
    "copy articles from 'https://cdn.crate.io/downloads/datasets/benchmarks/articles_0.json.gz' with (compression = 'gzip')",
    "copy colors from 'https://cdn.crate.io/downloads/datasets/benchmarks/colors_0.json.gz' with (compression = 'gzip')",
    "refresh table articles, colors"
]

[[queries]]
statement = "select id, name from articles union all select id, name from colors limit 100000"
iterations = 500

[[queries]]
statement = "select id, name from articles union all select id, name from colors order by 1, 2 limit 100000"
iterations = 250

[[queries]]
statement = "select id, name from articles union all select id, name from colors union all select id, name from articles union all select id,name from colors order by 1, 2 limit 400000"
iterations = 100

[teardown]
statements = ["drop table articles", "drop table colors"]
